# Generated by Django 3.1.6 on 2021-05-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210410_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='/static/images/dummy_image.png', null=True, upload_to='media'),
        ),
    ]
