# Generated by Django 3.1.6 on 2021-05-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210516_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectingpeople',
            old_name='connected_with',
            new_name='connection_receiver',
        ),
    ]
