# Generated by Django 3.1.6 on 2021-06-09 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
