# Generated by Django 3.1.6 on 2021-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210609_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_date',
            field=models.DateTimeField(default='2021-06-09 13:41:20'),
        ),
    ]
